remote_theme: yangby/yangby.github.io@theme
title: YangBy's GitHub Pages
description: My Point of View
author: yangby
javascript:
  mathjax:
    version: "3.1.2"
  google_analytics:
    tracking_id: UA-78583323-5
